### ISSUE TITLE
Integrare deploy automatico su Heroku al termine della conversione

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/covid-open-report-sicilia#21]
Non triggera quando il push avviene tramite action

**Comment by dennisangemi** [comment]
@gabacode credo che bisogna aggiungere 

```
  workflow_run:
    workflows: ["Download and convert PDF"]
    types:
      - completed
```

al file [`check_convert.yml`](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/.github/workflows/check_convert.yml)

come ho fatto qui con la action di frictionless https://github.com/opendatasicilia/covid-open-report-sicilia/commit/08c0ba1b7e102de4603d9d9e84431e145dfe967a

Ho fatto una PR (vedi sotto), lemme know se ti sembra ok
