### ISSUE TITLE
[frictionless] add constraints 

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#25]
pattern 2 decimal point: `^[0-9]*\.[0-9][0-9]$`

ref: https://stackoverflow.com/questions/4690986/regex-needed-to-match-number-to-exactly-two-decimal-places

frictionless datapackage:
```
  - name: blabla
    type: blabla
    description: blabla
    constraints:
      pattern: ^[0-9]*\.[0-9][0-9]$
```
